config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  #----------------------------------------------------
  # Index
  #----------------------------------------------------
  root 'dashboard#index'
  #----------------------------------------------------
  # Follow And Unfollow User
  #----------------------------------------------------
  get 'relationships/follow_user'
  get 'relationships/unfollow_user'
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user , :user_name => /[a-zA-Z0-9_\.]*/
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user ,:user_name => /[a-zA-Z0-9_\.]*/

  #----------------------------------------------------
  # Notifications
  #----------------------------------------------------
  resources :notifications do
    collection do
      post :mark_notifications_as_read
      post :mark_messages_notification_as_read
    end
  end
  #----------------------------------------------------
  # Making Devise to support preety url
  #----------------------------------------------------
  devise_scope :user do
    get "/register" => "devise/registrations#new", as: "new_user_registration"
  end
  devise_for :users, skip: [:sessions]
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  #----------------------------------------------------
  # Concerns for Post , Comments and Likes
  #----------------------------------------------------
  concern :postable do
    resources :posts ,except:[:new] do
      resources :comments,only:[:index,:create,:destroy]
      member do
        get 'like'
        get 'unlike'
      end
    end
  end

  #----------------------------------------------------
  #  Post witch concerns of post comment likes
  #----------------------------------------------------
  resources :users,only: [:show] ,concerns: :postable
  #----------------------------------------------------
  # Group
  #----------------------------------------------------
  resources :groups,concerns: :postable do
    member do
      get 'members',:as=>'members'

      post 'join/:user_id', :to => "groups#join", :as => 'join'
      post 'unjoin/:user_id', :to => "groups#unjoin", :as => 'unjoin'

      post 'approve/:user_id', :to => "groups#approve", :as => 'approve'
      post 'ban/:user_id', :to => "groups#ban", :as => 'ban'
      post 'delete/:user_id', :to => "groups#delete", :as => 'delete'

      post 'make_moderator/:user_id', :to => "groups#make_moderator", :as => 'make_moderator'
      post 'demote_moderator/:user_id', :to => "groups#demote_moderator", :as => 'demote_moderator'

      get 'chat', :to => "groups#chat", :as => 'chat'
    end
  end
  #----------------------------------------------------
  # Showing All Users
  #----------------------------------------------------
  get 'all-users', to: 'profiles#show_all_users'

  #----------------------------------------------------
  # Profile
  #----------------------------------------------------
  get 'profiles/show'
  get '@:user_name', to: 'profiles#show', as: :profile ,:user_name => /[a-zA-Z0-9_\.]*/
  get '@:user_name/edit', to: 'profiles#edit', as: :edit_profile , :user_name => /[a-zA-Z0-9_\.]*/
  patch '@:user_name/edit', to: 'profiles#update', as: :update_profile ,:user_name => /[a-zA-Z0-9_\.]*/

  #----------------------------------------------------
  # Chat Message
  #----------------------------------------------------
  resources :chat_rooms, only: [:new, :create, :show, :index]

  #----------------------------------------------------
  # Search
  #----------------------------------------------------
  get 'search' , to: 'dashboard#search'
  get 'about' , to: 'dashboard#about'
  #----------------------------------------------------
  # Personal Message
  #----------------------------------------------------
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]
  post 'conversations_api', to: 'personal_messages#api'

  mount ActionCable.server => '/cable'
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'

  validates :author, uniqueness: {scope: :receiver}
  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end

  def with(current_user)
    author == current_user ? receiver : author
  end

  def participates?(user)
    author == user || receiver == user
  end

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id)).limit(1)
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_conversation, except: [:index]
  before_action :check_participating!, except: [:index]

  def show
    @personal_message = PersonalMessage.new
    @conversations = Conversation.participating(current_user).order('updated_at DESC')

    respond_to do |format|
      format.html { render :layout => false } # your-action.html.erb
    end
  end

  def index
    @conversations = Conversation.participating(current_user).order('updated_at DESC')
  end

  private

  def set_conversation
    @conversation = Conversation.find_by(id: params[:id])
  end

  def check_participating!
    redirect_to root_path unless @conversation && @conversation.participates?(current_user)
  end

end

app/views/conversations/_conversation.html.haml
%div{:class => 'conversation_list_item'}
  = link_to  conversation_path(conversation) do
    .conversation_list_item__image
      = post_avatar_select(current_user)
    .conversation_list_item__text
      = link_to conversation.with(current_user).user_name,profile_path(conversation.with(current_user))
      %br
      .conversation_list_item__message
        = conversation.personal_messages.last.body.truncate(50)
    %div{style: 'clear:both'}

app/views/conversations/_personal_message.html.haml
%p= personal_message.body
%p
  at
  %strong= personal_message.created_at
  %br/
  by
  %strong= personal_message.user.user_name
%hr/

app/views/conversations/index.html.haml
.container
  .row
    .col-sm-4
      .conversation_box.list-group
        %li.list-group-item
          .chat_box_heading Conversations
        %li
          = render @conversations

    .col-sm-8
      %article.post-wrapper
      .post
        .post-head
          %p Click on left to any conversation to chat

app/views/conversations/show.html.haml
%header.chatboxhead
  .chatboxtitle
    = @conversation.with(current_user).user_name
  .chatboxoptions
    = link_to "<span class='glyphicon glyphicon-minus'></span> ".html_safe, "#", class: "toggleChatBox", "data-cid" => @conversation.id
    = link_to "<span class='glyphicon glyphicon-remove'></span> ".html_safe, "#", class: "closeChat", "data-cid" => @conversation.id

  %br{:clear => "all"}

.chatboxcontent
  - if @conversation.personal_messages.any?
    = render @conversation.personal_messages.order(created_at: :asc).last(100)
.chatboxinput
  = form_for([@personal_message], :html => {id: "conversation_form_#{@conversation.id}"})  do |f|
    = hidden_field_tag 'conversation_id', @conversation.id,class: 'conversation_id'
    = f.text_area :body, class: 'chatboxtextarea',label: false,autofocus: true ,"data-cid" => @conversation.id

  = simple_form_for([@personal_message], remote: true,:html => {multipart: true,id: "conversation_attachment_form_#{@conversation.id}"})  do |f|
    = hidden_field_tag 'conversation_id', @conversation.id,class: 'conversation_id'
    = hidden_field_tag 'personal_message[body]', "Uploaded File"
    .personal_message_attachment
      %span{class: "personal_attachment_upload glyphicon glyphicon-upload"}
      = f.input :attachment,label: false,wrapper: false
    %div{style: {clear: 'both'}}