config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  #----------------------------------------------------
  # Index
  #----------------------------------------------------
  root 'dashboard#index'
  #----------------------------------------------------
  # Follow And Unfollow User
  #----------------------------------------------------
  get 'relationships/follow_user'
  get 'relationships/unfollow_user'
  post ':user_name/follow_user', to: 'relationships#follow_user', as: :follow_user , :user_name => /[a-zA-Z0-9_\.]*/
  post ':user_name/unfollow_user', to: 'relationships#unfollow_user', as: :unfollow_user ,:user_name => /[a-zA-Z0-9_\.]*/

  #----------------------------------------------------
  # Notifications
  #----------------------------------------------------
  resources :notifications do
    collection do
      post :mark_notifications_as_read
      post :mark_messages_notification_as_read
    end
  end
  #----------------------------------------------------
  # Making Devise to support preety url
  #----------------------------------------------------
  devise_scope :user do
    get "/register" => "devise/registrations#new", as: "new_user_registration"
  end
  devise_for :users, skip: [:sessions]
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    delete 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  #----------------------------------------------------
  # Concerns for Post , Comments and Likes
  #----------------------------------------------------
  concern :postable do
    resources :posts ,except:[:new] do
      resources :comments,only:[:index,:create,:destroy]
      member do
        get 'like'
        get 'unlike'
      end
    end
  end

  #----------------------------------------------------
  #  Post witch concerns of post comment likes
  #----------------------------------------------------
  resources :users,only: [:show] ,concerns: :postable
  #----------------------------------------------------
  # Group
  #----------------------------------------------------
  resources :groups,concerns: :postable do
    member do
      get 'members',:as=>'members'

      post 'join/:user_id', :to => "groups#join", :as => 'join'
      post 'unjoin/:user_id', :to => "groups#unjoin", :as => 'unjoin'

      post 'approve/:user_id', :to => "groups#approve", :as => 'approve'
      post 'ban/:user_id', :to => "groups#ban", :as => 'ban'
      post 'delete/:user_id', :to => "groups#delete", :as => 'delete'

      post 'make_moderator/:user_id', :to => "groups#make_moderator", :as => 'make_moderator'
      post 'demote_moderator/:user_id', :to => "groups#demote_moderator", :as => 'demote_moderator'

      get 'chat', :to => "groups#chat", :as => 'chat'
    end
  end
  #----------------------------------------------------
  # Showing All Users
  #----------------------------------------------------
  get 'all-users', to: 'profiles#show_all_users'

  #----------------------------------------------------
  # Profile
  #----------------------------------------------------
  get 'profiles/show'
  get '@:user_name', to: 'profiles#show', as: :profile ,:user_name => /[a-zA-Z0-9_\.]*/
  get '@:user_name/edit', to: 'profiles#edit', as: :edit_profile , :user_name => /[a-zA-Z0-9_\.]*/
  patch '@:user_name/edit', to: 'profiles#update', as: :update_profile ,:user_name => /[a-zA-Z0-9_\.]*/

  #----------------------------------------------------
  # Chat Message
  #----------------------------------------------------
  resources :chat_rooms, only: [:new, :create, :show, :index]

  #----------------------------------------------------
  # Search
  #----------------------------------------------------
  get 'search' , to: 'dashboard#search'
  get 'about' , to: 'dashboard#about'
  #----------------------------------------------------
  # Personal Message
  #----------------------------------------------------
  resources :personal_messages, only: [:new, :create]
  resources :conversations, only: [:index, :show]
  post 'conversations_api', to: 'personal_messages#api'

  mount ActionCable.server => '/cable'
end

app/models/group.rb
class Group < ApplicationRecord
  validates :thumbnail_image, presence: true
  validates :timeline_image, presence: true
  validates :name, presence: true
  validates :description, presence: true

  has_attached_file :thumbnail_image #, styles: { :small => "330x" }
  has_attached_file :timeline_image #, styles: { :small => "330x" }

  validates_attachment_content_type :thumbnail_image, :content_type => /\Aimage\/.*\Z/
  validates_attachment_content_type :timeline_image, :content_type => /\Aimage\/.*\Z/

  has_many :posts,as: :postable

  has_many :group_memberships
  has_many :members,through: :group_memberships,source: :user

  has_many :group_message ,dependent: :destroy
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_group, only: [:show, :edit, :update, :destroy,:members]
  before_action :administration_right, only: [:create,:update,:destroy,:demote_moderator,:make_moderator]
  before_action :set_group_id_and_user_id_and_user, only: [:moderation_right,:delete,:approve,:ban,:make_moderator,:demote_moderator]
  before_action :moderation_right, only: [:delete,:approve,:ban,]

  def index
    @groups = Group.all
  end

  def new
    @group = Group.new
  end

  def edit
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to @group, notice: 'Group was successfully created.'
    else
       render :new
    end
  end

  def update
    if @group.update(group_params)
       redirect_to @group, notice: 'Group was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @group.destroy
    redirect_to groups_url, notice: 'Group was successfully deleted.'
  end

  def show
    @posts = @group.posts.order('created_at DESC').page params[:page]
    @post = @group.posts.build
  end

  def chat
    @group = Group.includes(:group_message).find_by(id: params[:id])
    @group_message = GroupMessage.new
  end

  def members
    @members = GroupMembership.includes(:group,:user).where(group_id: @group.id)
    @moderator_role_id = Role.where(name: 'moderator').first.id
    @approved_role_id = Role.where(name: 'group_approved').first.id
    @pending_role_id = Role.where(name: 'group_pending_approval').first.id
    @banned_role_id = Role.where(name: 'banned').first.id
  end

  def join
    @group_id = params[:id]
    @user_id = current_user.id
    if current_user.join_group_toggle @group_id
      render_js
    end
  end
  def unjoin
    @group_id = params[:id]
    @user_id = current_user.id
    if current_user.join_group_toggle @group_id
      render_js
    end
  end
  def delete
    @user = User.find(@user_id)
    if @user.delete_group_user @group_id
      render_js
    end
  end
  def approve
    if can_change_responsibility(@group_id,@user)
      role_update("group_approved")
      Notification.find_or_initialize_by(recipient: @user,actor: current_user,action: 'approved',notifiable: @group).update_attributes!(read_at: nil)
    end
  end
  def make_moderator
    if can_change_responsibility(@group_id,@user)
      role_update("moderator")
      Notification.find_or_initialize_by(recipient: @user,actor: current_user,action: 'promoted',notifiable: @group).update_attributes!(read_at: nil)
    end
  end
  def demote_moderator
    if can_change_responsibility(@group_id,@user)
      role_update("group_approved")
    end
  end
  def ban
    if can_change_responsibility(@group_id,@user)
      role_update("banned")
    end
  end

  private
    def group_params
      params.require(:group).permit(:name,:thumbnail_image,:timeline_image, :description)
    end
    def set_group
      @group = Group.find(params[:id])
    end
    def set_group_id_and_user_id_and_user
      @group_id = params[:id]
      @group = Group.find(@group_id)
      @user_id = params[:user_id]
      @user = User.find(@user_id)
    end

    def administration_right
      unless current_user.role.name =='admin'
        redirect_for_invalid_activity
      end
    end
    def moderation_right
      unless is_responsible_user(@group_id,current_user)
        redirect_for_invalid_activity
      end
    end
    def is_responsible_user(group_id,user)
      user.group_role_name(group_id) == 'moderator' or current_user.role.name =='admin'
    end
    def can_change_responsibility(group_id,user)
      !is_responsible_user(group_id,user) or current_user.role.name =='admin'
    end
    def redirect_for_invalid_activity
      flash[:alert] = "Only responsible person can accomplish such responsibility!"
      redirect_to groups_path
    end
    def role_update(role_name)
      if @user.group_role_update @group_id , role_name
        render_js
      else
        redirect_for_invalid_activity
      end
    end
    def render_js
      respond_to do |format|
        format.js
      end
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
  def current_user_is_joined(current_user_id, group_id)
    relationship = GroupMembership.find_by(user_id: current_user_id, group_id: group_id)
    return true if relationship
  end
  def moderation_links_and_power(post)
    return current_user == post.user || current_user.role.name =='admin' || (current_user.is_univerisity_moderator(post.postable.id) && !post.user.is_univerisity_moderator(post.postable.id))
  end
  def moderation_power(user,group)
    if current_user.role.name == 'admin'
        return true
    end
    if current_user.is_univerisity_moderator(group.id) && !user.is_univerisity_moderator(group.id)
      return true
    end
    if !current_user.is_univerisity_moderator(group.id)
      return false
    end
    return false
  end
end

app/views/groups/_form.html.haml
- if group.errors.any?
  #error_explanation
    %h4
      = pluralize(group.errors.count, "error")
      prohibited this group from being saved:
    %ul
      - group.errors.full_messages.each do |message|
        %li= message

= simple_form_for group, html: { multipart: true } do |f|
  = f.input :thumbnail_image, inline_label: 'Thummnail Image'
  = f.input :timeline_image, inline_label: 'Timeline Image'
  = f.input :name, label: false, placeholder: 'Group Name' ,:autofocus => true
  = f.input :description, label: false, placeholder: 'Group Description'
  = f.button :submit, class: 'btn-success btn-block'

app/views/groups/_join_group.html.haml
.mt20.bgwhite.sb1.padding20.mb20
  %p Please Join the group and wait for admin and wait for moderators to approve
  %p After joining only you are able to:
  %ul
    %li See Posts
    %li Create Interative Posts
    %li Share Images
    %li Share Files
    %li Chat With Group Members
    %li Comments on each other posts
    %li See the member of this group
  %p By joining this Group you agree with our terms and conditions

app/views/groups/_members_common_links.html.haml
%div{class: "padding20 bglgray sb1 dib w250 text-center" ,id: "user_box_#{member.user.id}"}
  = profile_avatar_select(member.user)
  %h6= link_to member.user.full_name,profile_path(member.user.user_name)
  - if(current_user.is_univerisity_moderator(@group.id))
    - if(type == 'pending')
      = link_to 'Approve',approve_group_path(group.id,member.user.id),class: 'btn btn-success',id:"approve_user_#{member.user.id}",remote: true,method: :post
    - if( (type == 'pending' or type =='moderators' or type =='members' or type =='banned') && moderation_power(member.user,group))
      = link_to 'Delete',delete_group_path(group.id,member.user.id),class: 'btn btn-danger',id:"delete_user_#{member.user.id}",remote: true,method: :post
    - if( (type == 'pending' or type =='moderators' or type =='members') && moderation_power(member.user,group) )
      = link_to 'Ban',ban_group_path(group.id,member.user.id),class: 'btn btn-warning',id:"ban_user_#{member.user.id}",remote: true,method: :post
    - if(current_user.is_group_admin(@group.id))
      -if(type == 'moderators')
        = link_to 'Demote',demote_moderator_group_path(group.id,member.user.id),class: 'btn btn-info',id:"demote_user_#{member.user.id}",remote: true,method: :post
      -if(type == 'members')
        = link_to 'Promote',make_moderator_group_path(group.id,member.user.id),class: 'btn btn-info',id:"promote_user_#{member.user.id}",remote: true,method: :post

app/views/groups/ban.js.erb
$('#ban_user_<%= @user_id %>').attr('class', 'btn btn-success') .text('Banned') .attr('href', "#").attr("disabled", true)

app/views/groups/chat.html.haml
.bgwhite.sb1.mt20.mwidth960.mauto.padding20
  = render 'common_links'
  %hr
  - if current_user.is_group_approved(@group.id)
    #group_messages{'data-group-id': @group.id }
      - @group.group_message.order(created_at: :asc).reverse_order().limit(150).each do |message|
        = render 'messages',message: message

    = form_for @group_message, url: '#' do |f|
      .form-group
        = f.text_area :body, class: 'form-control'
      = f.submit "Send Messages", class: 'btn btn-primary '

app/views/groups/delete.js.erb
$('#user_box_<%= @user_id %>').remove();

app/views/groups/demote_moderator.js.erb
$('#demote_user_<%= @user_id %>').attr('class', 'btn btn-success') .text('Demoted') .attr('href', "#").attr("disabled", true)

app/views/groups/edit.html.haml
.post-wrapper
  .post
    .padding20
      %h4 Editing Group
      = render 'form', group: @group
      = link_to 'Show', @group,class: 'btn btn-success'
      = link_to 'Back', groups_path,class: 'btn btn-primary'

app/views/groups/join.js.erb
$('#join_group_<%= @group_id %>').attr('class', 'btn btn-danger flat__buttons')
                   .text('Leave This Group')
                   .attr('href', "/groups/<%= @group_id %>/unjoin/<%= @user_id %>")

app/views/groups/make_moderator.js.erb
$('#promote_user_<%= @user_id %>').attr('class', 'btn btn-success') .text('Promoted') .attr('href', "#").attr("disabled", true)

app/views/groups/members.html.haml
.bgwhite.sb1.mt20.mwidth960.mauto.padding20
  = render 'common_links'
  %hr
  - if current_user.is_group_approved(@group.id)
    %h4 Moderators
    -@members.each do |member|
      -if(member.role_id == @moderator_role_id)
        = render 'members_common_links',group: @group , member: member,type: 'moderators'
    %hr
    %h4 Members
    -@members.each do |member|
      -if(member.role_id == @approved_role_id)
        = render 'members_common_links',group: @group , member: member,type: 'members'
    %hr
    - if current_user.is_group_approved(@group.id)
      - if(current_user.is_univerisity_moderator(@group.id))
        %h4 Pending To Be Approved
        -@members.each do |member|
          -if(member.role_id == @pending_role_id)
            = render 'members_common_links',group: @group , member: member,type: 'pending'
          %hr
        %h4 Banned Users
        -@members.each do |member|
          -if(member.role_id == @banned_role_id)
            = render 'members_common_links',group: @group , member: member,type: 'banned'
        %hr
  - else
    = render 'join_group'

app/views/groups/new.html.haml
.post-wrapper
  .post
    .padding20
      %h4 Creating New Group:
      = render 'form', group: @group
      = link_to 'Back', groups_path,class: 'btn btn-primary'

app/views/groups/show.html.haml
.group-show-wrapper
  .group-timeline
    = link_to (image_tag @group.timeline_image.url(:original), class: 'group_timeline_image' ),groups_path(@group)
  .container-fluid
    .row
      .col-sm-8
        = render 'common_links'
        - if current_user.is_group_approved(@group.id)
          %main#posts
            .post-wrapper
              .post
                .padding20
                  = render 'posts/form',{post: @post,postable: @group}
            = render 'posts/posts',{posts: @posts,postable: @group}
          #paginator.text-center
            = link_to_next_page @posts, 'Load More', remote: true, id: 'load_more'
        - else
          = render 'join_group'
      .col-sm-4
        .post-wrapper
          = render 'join_and_unjoin_button',group:@group,user:current_user
          - if current_user.is_group_approved(@group.id)
            .post-wrapper
              .post
                .post-head
                  %h4 Description
                  = @group.description

app/views/groups/unjoin.js.erb
$('#join_group_<%= @group_id %>').attr('class', 'btn btn-success flat__buttons')
                   .text('Join This Group')
                   .attr('href', "/groups/<%= @group_id %>/join/<%= @user_id %>")